### ISSUE TITLE
simple-ajax removes my query string parameter

### ISSUE THREAD

**Issue by gavacho** [MauriceButler/simple-ajax#2]
A characteristic about query string parameters is that they're not enforced to be unique.  We often take advantage of this by sending arrays of values like `example.com/?param=a&param=b`.  Unfortunately, simple-ajax represents query string parameters as a hash (internally) and this results in the loss of data.  Additionally, you might consider supporting array values in your `toQueryString` function the way that jquery does: http://jsfiddle.net/g72nuz85/

**Comment by MauriceButler** [comment]
Hi Mate, nice catch. fixed in 2.0.0
